import { Activity, AlertTriangle, Package, RadioTower, ArrowRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useEffect, useState } from 'react'
import { getAlerts, getDashboard, getShipments } from '../services/mockAdapter'
import type { Alert, DashboardSummary, Shipment } from '../types'
import { PageHeader } from '../components/PageHeader'
import { StatCard } from '../components/StatCard'
import { TelemetryChart } from '../components/TelemetryChart'
import { StatusBadge } from '../components/StatusBadge'
import { LoadingState } from '../components/LoadingState'
export function DashboardPage() {
  const [summary, setSummary] = useState<DashboardSummary>(); const [alerts, setAlerts] = useState<Alert[]>([]); const [shipments, setShipments] = useState<Shipment[]>([])
  useEffect(() => { void Promise.all([getDashboard(), getAlerts(), getShipments()]).then(([s, a, sh]) => { setSummary(s); setAlerts(a); setShipments(sh) }) }, [])
  if (!summary) return <LoadingState />
  return <><PageHeader eyebrow="Operations overview" title="Good morning, Alex" description="Here's what's happening across your cold-chain network." action={<button className="btn btn-primary">Export snapshot</button>} /><div className="stats-grid"><StatCard label="Total devices" value={summary.totalDevices} detail="↑ 8.4% vs last month" icon={RadioTower} /><StatCard label="Online devices" value={`${Math.round(summary.onlineDevices / summary.totalDevices * 100)}%`} detail={`${summary.onlineDevices} of ${summary.totalDevices} reporting`} icon={Activity} /><StatCard label="Active shipments" value={summary.activeShipments} detail="↑ 2 new today" icon={Package} /><StatCard label="Open alerts" value={summary.openAlerts} detail="Needs attention" icon={AlertTriangle} tone="warning" /></div><div className="grid-2"><section className="card"><div className="card-header"><div><h2>Temperature telemetry</h2><p>Network average · Last 12 hours</p></div><span className="status online">Live</span></div><div className="card-body"><TelemetryChart data={summary.telemetry} /></div></section><section className="card"><div className="card-header"><div><h2>Recent alerts</h2><p>Prioritized by severity</p></div><Link className="btn" to="/alerts">View all <ArrowRight size={14} /></Link></div><div className="card-body"><div className="alert-list">{alerts.slice(0, 3).map((alert) => <div className={`alert-item ${alert.severity === 'warning' ? 'warning' : ''}`} key={alert.id}><div className="alert-icon"><AlertTriangle size={16} /></div><div className="alert-copy"><strong>{alert.title}</strong><p>{alert.device} · {alert.value}</p><small style={{ color: 'var(--muted)' }}>{alert.createdAt}</small></div><StatusBadge value={alert.status} /></div>)}</div></div></section></div><section className="card table-card" style={{ marginTop: 20 }}><div className="card-header"><div><h2>Active shipments</h2><p>Live shipment status across the network</p></div><Link className="btn" to="/shipments">Manage shipments <ArrowRight size={14} /></Link></div><div className="table-wrap"><table><thead><tr><th>Reference</th><th>Route</th><th>Cargo</th><th>Status</th><th>Temperature</th><th>ETA</th></tr></thead><tbody>{shipments.map((shipment) => <tr key={shipment.id}><td><Link to={`/shipments/${shipment.id}`} style={{ color: 'var(--blue)', fontWeight: 700 }}>{shipment.reference}</Link></td><td>{shipment.origin} → {shipment.destination}</td><td>{shipment.cargo}</td><td><StatusBadge value={shipment.status} /></td><td>{shipment.temperature}°C</td><td>{shipment.eta}</td></tr>)}</tbody></table></div></section></>
}
