import { ArrowLeft, Battery, MapPin, RadioTower } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { useEffect, useState } from 'react'
import { getDevice, getTelemetry } from '../services/mockAdapter'
import type { Device, TelemetryPoint } from '../types'
import { StatusBadge } from '../components/StatusBadge'
import { TelemetryChart } from '../components/TelemetryChart'
import { LoadingState } from '../components/LoadingState'
export function DeviceDetailPage() { const { id } = useParams(); const [device, setDevice] = useState<Device>(); const [data, setData] = useState<TelemetryPoint[]>([]); useEffect(() => { if (id) { void getDevice(id).then(setDevice); void getTelemetry().then(setData) } }, [id]); if (!device) return <LoadingState label="Loading device…" />; return <><Link to="/devices" className="btn" style={{ marginBottom: 18 }}><ArrowLeft size={15} /> Back to devices</Link><div className="page-heading"><div><div className="eyebrow">Device detail</div><h1>{device.name}</h1><p>{device.code} · {device.type}</p></div><StatusBadge value={device.status} /></div><div className="detail-grid"><div><section className="card detail-card"><div className="card-header" style={{ padding: 0 }}><div><h2>Temperature history</h2><p>Last 12 hours · updates every 30 seconds</p></div><span className="status online">Live</span></div><div style={{ marginTop: 20 }}><TelemetryChart data={data} /></div></section><section className="card detail-card"><h2>Device activity</h2><div className="alert-list" style={{ marginTop: 14 }}><div className="alert-item"><RadioTower size={18} color="var(--teal)" /><div className="alert-copy"><strong>Telemetry sync successful</strong><p>All readings received within expected interval.</p></div><small>2 min ago</small></div><div className="alert-item"><Battery size={18} color="var(--teal)" /><div className="alert-copy"><strong>Battery health stable</strong><p>Estimated 18 days remaining at current rate.</p></div><small>Today, 08:40</small></div></div></section></div><aside><section className="card detail-card"><h2>Current readings</h2><div className="detail-kpis"><div className="detail-kpi"><span>Temperature</span><strong>{device.temperature}°C</strong></div><div className="detail-kpi"><span>Humidity</span><strong>{device.humidity}%</strong></div><div className="detail-kpi"><span>Battery</span><strong>{device.battery}%</strong></div></div><div style={{ marginTop: 24, color: 'var(--muted)', fontSize: 13 }}><MapPin size={15} style={{ verticalAlign: 'middle', marginRight: 6 }} />{device.location}<br /><span style={{ marginLeft: 21 }}>Last seen {device.lastSeen}</span></div></section><section className="card detail-card"><h2>Actions</h2><div style={{ display: 'grid', gap: 10, marginTop: 16 }}><button className="btn">Configure thresholds</button><button className="btn">Send test reading</button><button className="btn btn-danger">Retire device</button></div></section></aside></div></> }
