import { ArrowLeft, CheckCircle2, CircleDot, MapPin } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { useEffect, useState } from 'react'
import { getShipment } from '../services/mockAdapter'
import type { Shipment } from '../types'
import { StatusBadge } from '../components/StatusBadge'
import { MapPlaceholder } from '../components/MapPlaceholder'
import { LoadingState } from '../components/LoadingState'
export function ShipmentDetailPage() { const { id } = useParams(); const [shipment, setShipment] = useState<Shipment>(); useEffect(() => { if (id) void getShipment(id).then(setShipment) }, [id]); if (!shipment) return <LoadingState label="Loading shipment…" />; return <><Link to="/shipments" className="btn" style={{ marginBottom: 18 }}><ArrowLeft size={15} /> Back to shipments</Link><div className="page-heading"><div><div className="eyebrow">Shipment detail</div><h1>{shipment.reference}</h1><p>{shipment.cargo}</p></div><StatusBadge value={shipment.status} /></div><div className="detail-grid"><div><section className="card detail-card"><h2>Live route</h2><p style={{ color: 'var(--muted)', fontSize: 13 }}>{shipment.origin} to {shipment.destination} · Device {shipment.deviceId}</p><div style={{ margin: '18px 0' }}><MapPlaceholder /></div><div className="detail-kpis"><div className="detail-kpi"><span>Temperature</span><strong>{shipment.temperature}°C</strong></div><div className="detail-kpi"><span>ETA</span><strong style={{ fontSize: 14 }}>{shipment.eta}</strong></div><div className="detail-kpi"><span>Integrity</span><strong style={{ color: 'var(--success)', fontSize: 14 }}>On track</strong></div></div></section><section className="card detail-card"><h2>Journey timeline</h2><div className="alert-list" style={{ marginTop: 15 }}><div className="alert-item"><CheckCircle2 color="var(--success)" size={18} /><div className="alert-copy"><strong>Departed {shipment.origin}</strong><p>Shipment departed origin facility.</p></div><small>Today, 06:25</small></div><div className="alert-item"><CircleDot color="var(--blue)" size={18} /><div className="alert-copy"><strong>In transit</strong><p>Temperature remains within 2–8°C threshold.</p></div><small>Current</small></div><div className="alert-item"><MapPin color="var(--muted)" size={18} /><div className="alert-copy"><strong>Arrive {shipment.destination}</strong><p>Expected delivery window.</p></div><small>{shipment.eta}</small></div></div></section></div><aside><section className="card detail-card"><h2>Shipment details</h2><div style={{ display: 'grid', gap: 17, marginTop: 18, fontSize: 13 }}><div><span style={{ color: 'var(--muted)', display: 'block' }}>Origin</span><strong>{shipment.origin}</strong></div><div><span style={{ color: 'var(--muted)', display: 'block' }}>Destination</span><strong>{shipment.destination}</strong></div><div><span style={{ color: 'var(--muted)', display: 'block' }}>Monitoring device</span><Link to={`/devices/${shipment.deviceId}`} style={{ color: 'var(--blue)', fontWeight: 700 }}>{shipment.deviceId}</Link></div></div></section></aside></div></> }
